### ISSUE TITLE
Unkown function ExpandMap

### ISSUE THREAD

**Issue by j-hui** [LunarWatcher/auto-pairs#13]
Thanks for forking this and working on those issues! I tried this out but encountered some issues.

**OS**: NixOS
**What vim? (+ version)**: nvim 0.4.4
**Reproduced in other variants of Vim?** (Optional): vim 8.2.1522

**Describe the bug**
When starting {n,}vim, I get the following error:

```E117: Unknown function: ExpandMap```

**Steps to reproduce**

Put the following in `~/.vimrc`: 

```
Plug 'LunarWatcher/auto-pairs'
```
(with or without `{ 'tag': '*''}` argument)

`:PlugInstall`.

Issue seems to be due to [`call ExpandMap(...)`](https://github.com/LunarWatcher/auto-pairs/blob/master/autoload/autopairs.vim#L843), although `ExpandMap` appears to have been defined as follows:

```func! autopairs#ExpandMap(map)```

**Comment by LunarWatcher** [comment]
My bad, only happens in old versions of vim where info returns something that evaluates to false. Regex doesn't always cut it xd No repro locally because Vim 8.2.2256.

Gonna do another proper sweep for unmigrated functions tomorrow. Thought I got them all last time :woman_facepalming:
