### ISSUE TITLE
GetFirstUnicodeChar does not handle case where strgetchar() returns -1

### ISSUE THREAD

**Issue by j-hui** [LunarWatcher/auto-pairs#14]
Thanks for forking this and working on those issues! I tried this out but encountered some issues.

**OS**: NixOS
**What vim? (+ version)**: nvim 0.4.4
**Reproduced in other variants of Vim? (Optional)**: N/A

(I actually tried this on vim 8.2.1522 and could not reproduce there, interestingly.)

**Describe the bug**
When starting nvim, I get the following error:

```
Error detected while processing function autopairs#AutoPairsTryInit[70]..autopairs#AutoPairsInit[33]..<SN
R>154_GetFirstUnicodeChar:
line    1:
E5070: Character number must not be less than zero
```

**Steps to reproduce**

Install and start.

**Suggested fix**

Something like this appears to have fixed the issue, but I haven't gotten around to testing this on any actual unicode characters... once I get around to that I'm happy to make a PR, if you're accepting any (:

```
diff --git i/autoload/autopairs.vim w/autoload/autopairs.vim
index c528092..9b077d5 100644
--- i/autoload/autopairs.vim
+++ w/autoload/autopairs.vim
@@ -98,11 +98,21 @@ endf

 " Idea by https://github.com/fenuks: https://github.com/jiangmiao/auto-pairs/issues/251#issuecomment-573901691
 fun! s:GetFirstUnicodeChar(string)
-  return nr2char(strgetchar(a:string, 0))
+  let l:nr = strgetchar(a:string, 0)
+  if l:nr == -1
+    return ""
+  else
+    return nr2char(l:nr)
+  endif
 endfun

 fun! s:GetLastUnicodeChar(string)
-  return nr2char(strgetchar(a:string, strchars(a:string) - 1))
+  let l:nr = strgetchar(a:string, strchars(a:string) - 1)
+  if l:nr == -1
+    return ""
+  else
+    return nr2char(l:nr)
+  endif
 endfun
```

**Comment by LunarWatcher** [comment]
Feel free to make a PR; gonna test the patch tomorrow either way though, regardless of whether there's a PR or not. Just for good measure, have you modified any of the pairs, or is it all default? Kinda sus it's related to the empty pairs, in which case it might be enough to do an empty check instead of this, or maybe both. Only repro in nvim is interesting though -- maybe there's differences in how they handle unicode?

**Comment by LunarWatcher** [comment]
Merged in your patch -- thanks!

**Comment by j-hui** [comment]
Yeah, not really sure why it worked on Vim.. glad it works and that you merged it in!
