### ISSUE TITLE
ShortcutJump doesn't work for added pairs

### ISSUE THREAD

**Issue by shadowspiral** [LunarWatcher/auto-pairs#16]
**OS** : ArchLinux Kernel 5.10.11
**What vim? (+ version)** : Neovim 0.4.4
**Reproduced in other variants of Vim?**: No

**Autopairs config** (if applicable):
```
Plug 'LunarWatcher/auto-pairs', { 'tag' : '*' }
au FileType tex let b:AutoPairs = autopairs#AutoPairsDefine({'$' : '$'})
```

**Describe the bug**

The added pairs do not count when ShortcutJump is pressed.

**Steps to reproduce**

Example with provided configuration (I've tried with other pairs and the same behavior persists)

Before(Cursor at `|`):
```
$|${

}
```
Result after `<M-n>`
```
$${

}|
```
What should happen
```
$$|{

}
```

**Comment by LunarWatcher** [comment]
`autopairs#AutoPairsJump` isn't linked against `g:AutoPairs`.

**Comment by shadowspiral** [comment]
It still persists.

**Comment by LunarWatcher** [comment]
If you're still using the latest tag, switch over to the master branch. Haven't made another release yet

**Comment by shadowspiral** [comment]
Oh, sorry! Yes it is fixed now. Thanks for the swift fix!

**Comment by LunarWatcher** [comment]
No problem! ^^
