### ISSUE TITLE
Fix the meta mappings

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/auto-pairs#18]
They're dumb and need to die in a fire kthxinadvance.

Seriously though, there has to be some untapped ctrl keybind for the various parts that can be used. Can't really touch `<leader>` either, which largely leaves ctrl.

The second problem here is backwards compatibility; there's a few people who use this fork, and I doubt suddenly changing it is gonna sit well. Might be a good idea to add a transitional switch variable or something. iDunno, and this isn't a job for 1:08 me, but rather future me

**Comment by kuntau** [comment]
Hey I just use your fork instead of the outdated original auto-pairs. Do you mean meta mapping in the insert mode?

**Comment by LunarWatcher** [comment]
Yeah, some of which overlap with normal mode mappings (largely for consistency I guess). The insert ones are largely problematic because of overlap with mostly european characters. I don't think there's pure normal mode maps, though.
