### ISSUE TITLE
Auto delete pair & auto jump

### ISSUE THREAD

**Issue by kuntau** [LunarWatcher/auto-pairs#19]
**OS** : MacOS Catalina
**What vim? (+ version)** (i.e. vim, gvim, nvim, nvim-qt, mvim, ...): nvim HEAD
**Reproduced in other variants of Vim?** (Optional):

**Autopairs config** (if applicable):

**Describe the bug**

Hi, I'm new to your fork. Right away after installing I noticed some difference with jiangmiao default.

There's no configuration. Just default install with vim-plug

1. After typing closing tag `}])` it's not jumping to the closing tag instead those literal character was added.
2. `Backspace` after auto insert matching tag don't delete the matching tag eg left the with `)}]`

Is there any settings I have to set? This is on javascript file

**Steps to reproduce**

**Comment by LunarWatcher** [comment]
For 1: Can I get some more context? What's the opening pair like? What code are we talking about? 

For 2: Mapping backspace is disabled by default in this fork 

https://github.com/LunarWatcher/auto-pairs/blob/master/doc/AutoPairs.txt#L390-L398

Try `let g:AutoPairsMapBS = 1` and see if that helps.

**Comment by kuntau** [comment]
Please see this replay 

https://asciinema.org/a/h6b1secmQthYM8fzfvrGAMXJk

**Comment by LunarWatcher** [comment]
Something broke that, but I could've sworn I fixed that a while ago. Gonna grab some food and have a look

**Comment by LunarWatcher** [comment]
1 requires `let g:AutoPairsMultilineClose = 1` - gonna change the default back to 1. (Originally changed to 0 by Krasjet)

**Comment by kuntau** [comment]
> 1 requires `let g:AutoPairsMultilineClose = 1` - gonna change the default back to 1. (Originally changed to 0 by Krasjet)

Perfect. Thank you

**Comment by LunarWatcher** [comment]
I _think_ that should do the trick. Can you try now?

**Comment by LunarWatcher** [comment]
I'm gonna assume it's fine now.  If it's still broken, reopen this issue, open a new issue, or leave a comment here

**Comment by kuntau** [comment]
Hi. Thank you for the quick fix. Looks like I can't use it yet since I use the recommended `Tag *` 👍🏽

**Comment by LunarWatcher** [comment]
Right, just made another tag
