### ISSUE TITLE
Auto pairs delete random text on <backspace>

### ISSUE THREAD

**Issue by kuntau** [LunarWatcher/auto-pairs#22]
**OS** (name + version; i.e. Linux Mint 20, Windows 10 2004, Macos Big Sur, etc.): OSX
**What vim? (+ version)** (i.e. vim, gvim, nvim, nvim-qt, mvim, ...): nvim
**Reproduced in other variants of Vim?** (Optional):

**Autopairs config** (if applicable): `let g:AutoPairsMapBS=1`

**Describe the bug**

I thought I was going crazy. Something was deleting more than it supposed to when pressing `backspace`

Upon investigating my recent change, I found out it was auto-pairs. This weird behavior gone after I disable auto-pairs.

[You can see from the this asciinema.](https://asciinema.org/a/ZkRJKhUrhXozSSwbxhPdgWqSB) Each deletion is actually 1 keystroke of backspace

    https://asciinema.org/a/ZkRJKhUrhXozSSwbxhPdgWqSB

**Steps to reproduce**

I think this have something todo with `let g:AutoPairsMapBS=1`

**Comment by LunarWatcher** [comment]
Is it limited to vimscript? Got a ridiculous regex in there that may be to blame. I haven't touched backspace that much though, so I can't see why it'd break aside edge cases. Gonna see if I can repro when I get out of bed 😅

**Comment by LunarWatcher** [comment]
No repro in vim, gvim, or nvim. What's the output of `:verbose imap <bs>`?

**Comment by LunarWatcher** [comment]
... scratch that. Repro'd in vimscript on this project by randomly forgetting to turn off `<BS>` before starting.

**Comment by LunarWatcher** [comment]
I've pushed a patch for this and one other bug in `<BS>`. When it's possible to repro beats me though. Managed to repro in autopairs' code, but not in the code included in your asciinema.

Seems to be related to enabling `foo[]|<BS> => foo|`-deletion, but I have no idea why it's only being triggered now.

The master branch contains a patch for it if you need it _right now_. If not, I have a few other things I need to fix, but beta7 should be a thing before midnight UTC+1

**Comment by kuntau** [comment]
FWIW, happened in JS codes too.. I'll try master later. Thank you

**Comment by LunarWatcher** [comment]
I*m gonna assume this is fine now and close the issue. If it's still broken, leave a comment and reopen, and I'll take a look at it. Also created beta7, so the update is available on a tag now
