### ISSUE TITLE
Wow so you are 160 commits ahead of jiangmiao should we just use your fork then?

### ISSUE THREAD

**Issue by richtong** [LunarWatcher/auto-pairs#24]
Happy to do it and super confused right now about how to disable autopairs it says the command is <M-p> which on a Mac Meta is mapped to the ESC key right so should be ESC-p, but this just bleeps at me

**Comment by LunarWatcher** [comment]
Assuming you don't find another plugin you like more, sure. I've also been keeping up to date on upstream issues 

The meta mappings have been partially phased out; they're enabled by default purely for backwards compatibility. If you set [g:AutoPairsCompatibleMaps](https://github.com/LunarWatcher/auto-pairs/blob/master/doc/AutoPairs.txt#L932-L948) to 0, `<C-p><C-t>` (mnemonic: c-pairs c-toggle). Is that what you meant, or did I misunderstand?

The meta mappings, at least in insert mode, inherently have several problems - I had no idea weird mac behavior was one of them ^^" I guess that's another reason to throw in the pile of justification for changing the maps

And as always, if you don't like the maps (or they for other reasons cause problems, like by conflict, or various specific OS behavior), there's variables to change them; [`g:AutoPairsShortcutToggle`](https://github.com/LunarWatcher/auto-pairs/blob/master/doc/AutoPairs.txt#L361-L367).

**Comment by richtong** [comment]
Yes that’s great. I flipped this on. And it works great. The document is pretty unclear about the four command. As I try to parse the doc I don’t really get what jump does b

Sent via Superhuman iOS ( https://sprh.mn/?vip=rich@tongfamily.com )

**Comment by LunarWatcher** [comment]
It's largely explained in the name, but I can rewrite those sections a bit. The jump keybind is literally just "jump to the first closed pair after the cursor"

**Comment by richtong** [comment]
Ah got it!!!

Sent via Superhuman iOS ( https://sprh.mn/?vip=rich@tongfamily.com )
