### ISSUE TITLE
How to delete pairs when there is a blank newline?

### ISSUE THREAD

**Issue by caoshenghui** [LunarWatcher/auto-pairs#29]
**OS** (name + version; ): win10 wsl2
**What vim? (+ version)** : vim 8.2.2539
**Reproduced in other variants of Vim?** (Optional):

**Autopairs config** (if applicable):

**Describe the bug**

**Steps to reproduce**

```txt
before:
{
    |
}
```
Now I want to delete pairs, use backspace three times
```txt
after:
|
}
```
```txt
except: 
|
```

**Comment by LunarWatcher** [comment]
Fixed on the master branch - `let g:AutoPairsMultilineBackspace = 1`. I've also published v3.0.0-beta8 now, so it's tagged as well.

The TL;DR: here is that this got knocked out when removing some other multiline stuff (that was way too aggressive and caused matching problems for balancing, deletion, and other stuff). I added that variable to reenable it for backspace.

**Comment by caoshenghui** [comment]
I has updated, sorry to tell you it can't work correctly. 
```txt
{|}

after backspace:

|}

result: can't work, before update it works correctly.
```
when I set `let g:AutoPairsMultilineBackspace = 1`, it can't work as well

**Comment by LunarWatcher** [comment]
See #27

**Comment by caoshenghui** [comment]
Thanks for your help!
