### ISSUE TITLE
Second single quote in a line is missing a corresponding pair

### ISSUE THREAD

**Issue by pjg** [LunarWatcher/auto-pairs#30]
**OS** MacOS Catalina (10.15.7):
**What vim? (+ version)** (i.e. vim, gvim, nvim, nvim-qt, mvim, ...): MacVim (8.2.2576 (170))
**Reproduced in other variants of Vim?** (Optional):

**Describe the bug**

Second single quote in a line is missing a corresponding pair

**Steps to reproduce**

1. Javascript filetype
2. Type: `func('` -- corresponding autoclosing pairs are inserted: `func('')`
3. Continue typing: `func('').func('` and only closing bracket is inserted (apostrophe is missing): `func('').func(')`

**Comment by LunarWatcher** [comment]
I think that should fix it. released v3.0.0-beta8 today, which includes a bit of new balance logic. Mistakes were made in the process :')

**Comment by pjg** [comment]
Thanks, that fixed it!
