### ISSUE TITLE
Potential incompatibility with vim views

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/auto-pairs#33]
See #192 -- I have no idea how to reproduce it (in fact, I can't repro with this fork or with the source repo), and much less how to fix it. Just messing with `mkview` and `loadview` isn't enough to trigger it, so I don't know when it's triggered either.

The fact that I can't reproduce it on either means that I have no idea whether it's fixed in this fork or not, as a happy side-effect of some other change.

It's not dependent on a specific version of Vim - someone in that issue reproduced it in a version compiled on 22.04.21, making it applicable to even new versions of Vim. It being reproduced in nvim as well as outside spf13/spf13-vim indicates that it's not just incompatibility with a vim distribution.

**Comment by timmyjose** [comment]
Hello, I saw you over on the original issue page. I just thought I'd try and help reproduce that issue if I could. For that, I installed your plugin using vim-plug, created a file, did some random changes, uninstalled your plugin, and then removed the whole `~/.vim/plugged` directory, and re-installed my old plugins. 

When I opened the original file that I'd been tinkering with, I had this pop-up (taken from the `messages` buffer):

![Screenshot 2021-04-28 at 8 08 43 PM](https://user-images.githubusercontent.com/2051158/116423057-f887b400-a85d-11eb-9f46-072e10bf6fc3.png)

The only lines relevant to views in my `.vimrc` are the following:

```
" save and load views automatically
augroup save_and_load_folds
  autocmd!
  autocmd BufWinLeave * mkview
  autocmd BufWinEnter * silent! loadview
augroup end
```
Maybe this could help your reproduce the issue? Some state somewhere is getting corrupted somehow.

After I got rid of the ~/.vim/view` directory, the errors stopped popping up.

**Comment by timmyjose** [comment]
(Note: ignore the misleading name for the `augroup` - just a mnemonic for my (practically) only use-case for views).

**Comment by LunarWatcher** [comment]
Oh, I see. I missed the part about plugin removal. Whoops :sweat_smile:

It'd seem that the view files end up storing the maps:
```
inoremap <buffer> <silent> <M-(> =AutoPairsMoveCharacter('(')
inoremap <buffer> <silent> <M-)> =AutoPairsMoveCharacter(')')
inoremap <buffer> <silent> <M-[> =AutoPairsMoveCharacter('[')
inoremap <buffer> <silent> <M-]> =AutoPairsMoveCharacter(']')
inoremap <buffer> <silent> <M-{> =AutoPairsMoveCharacter('{')
inoremap <buffer> <silent> <M-}> =AutoPairsMoveCharacter('}')
inoremap <buffer> <silent> <M-"> =AutoPairsMoveCharacter('"')
inoremap <buffer> <silent> <M-'> =AutoPairsMoveCharacter('''')
inoremap <buffer> <silent> <BS> =AutoPairsDelete()
inoremap <buffer> <silent> <C-H> =AutoPairsDelete()
inoremap <buffer> <silent> <M-e> =AutoPairsFastWrap()
inoremap <buffer> <silent> <M-b> =AutoPairsBackInsert()
inoremap <buffer> <silent> <expr> <M-p> AutoPairsToggle()
anoremap <buffer> <silent> <M-n> call AutoPairsJump()
inoremap <buffer> <silent> ¨ =AutoPairsMoveCharacter('(')
inoremap <buffer> <silent> © =AutoPairsMoveCharacter(')')
inoremap <buffer> <silent> ¢ =AutoPairsMoveCharacter('"')
inoremap <buffer> <silent> § =AutoPairsMoveCharacter('''')
inoremap <buffer> <silent> Û =AutoPairsMoveCharacter('[')
[the list continues]
```

Unfortunately, it seems there's not much to do about this after the fact - the view files have to be manually purged when uninstalling. Alternatively, `set viewoptions-=options` works, though that doesn't work if the goal is to save options; see https://stackoverflow.com/a/44066065/6296561. Again, doesn't work after the fact, but it's at least enough to prevent problems in the future if all you want is to save folds. There doesn't seem to be a way to exclude specific mappings from being saved either, but there's not a lot of documentation or options to use here, so iDunno. Looks like documentation is the best option here.

Thanks for the reproduction help though! ^^

**Comment by timmyjose** [comment]
Cheers for looking into the issue! As you said, this could probably just go into the documentation.

**Comment by eirnym** [comment]
Options save _local_ options and mappings as it's said in documentation. It shouldn't save any other mappings. 

If it's happened, I'd put an issue to Vim itself

**Comment by LunarWatcher** [comment]
All the mappings are buffer maps. I assumed that's why they were included.

**Comment by eirnym** [comment]
So am I correct that when I'm opening new buffer this plugin sets buffer-local bindings?

**Comment by LunarWatcher** [comment]
Yeah, and quite a few of them.

**Comment by eirnym** [comment]
Never know that, thank you
