### ISSUE TITLE
Inserting the character 'å' (norwegian qwerty keyboard) will not work while running the plugin

### ISSUE THREAD

**Issue by morngrar** [LunarWatcher/auto-pairs#42]
**OS** (name + version; i.e. Linux Mint 20, Windows 10 2004, Macos Big Sur, etc.):
Fedora 34

**What vim? (+ version)** (i.e. vim, gvim, nvim, nvim-qt, mvim, ...):
Vim 8.2 included patches 1-3391

**Reproduced in other variants of Vim?** (Optional):

**Autopairs config** (if applicable):

**Describe the bug**

Simply having the plugin installed and active with vim-plug results in the letter navigating in insert mode instead of being inserted.

**Steps to reproduce**

Change to a norwegian keyboard layout and hit the 'å' key, which you find just right of the letter 'P'.

**Comment by LunarWatcher** [comment]
This is a known issue, and one I've addressed (but for compatibility, this is not currently done by default). Use `let g:AutoPairsCompatibleMaps = 0` to switch to control-based maps instead. 

Relevant documentation:

https://github.com/LunarWatcher/auto-pairs/blob/master/doc/AutoPairs.txt#L55-L57

https://github.com/LunarWatcher/auto-pairs/blob/master/doc/AutoPairs.txt#L319-L324

https://github.com/LunarWatcher/auto-pairs/blob/master/doc/AutoPairs.txt#L1316-L1332

https://github.com/LunarWatcher/auto-pairs/blob/master/doc/AutoPairs.txt#L1579-L1605
