### ISSUE TITLE
Documentation cleanup

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/auto-pairs#45]
The docs have grown pretty fast, and gotten a bit messy; double-checking everything for accuracy, as well as shortening and re-writing for style, grammar, and clarity is needed.

It's primarily AutoPairs.txt in the `doc` directory that needs to be updated; it contains a lot of old text that I haven't focused on when doing other stuff. The things that need to be done are;

* [x] Spell-check and verify the readability of both the documentation files
* [x] Ensure technical accuracy in `AutoPairs.txt`, wrt. updates making certain parts obsolete
* [x] Changing the style in `AutoPairs.txt`, if necessary to improve readability
* [x] Making stuff easier to find in `AutoPairs.txt`

Also note that this is a lot for a single PR, so anything fixing or working on parts of this are fine; there's a lot of text to go through, and a lot of stuff to improve, so partial pull pull requests are obviously fine.

**Comment by qwe123coder** [comment]
hey could i do this

**Comment by LunarWatcher** [comment]
Sure!

**Comment by qwe123coder** [comment]
> The docs have grown pretty fast, and gotten a bit messy; double-checking everything for accuracy, as well as shortening and re-writing for style, grammar, and clarity is needed.
> 
> It's primarily AutoPairs.txt in the `doc` directory that needs to be updated; it contains a lot of old text that I haven't focused on when doing other stuff. The things that need to be done are;
> 
> * [ ]  Spell-check and verify the readability of both the documentation files
> * [ ]  Ensure technical accuracy in `AutoPairs.txt`, wrt. updates making certain parts obsolete
> * [ ]  Changing the style in `AutoPairs.txt`, if necessary to improve readability
> * [ ]  Making stuff easier to find in `AutoPairs.txt`
> 
> Also note that this is a lot for a single PR, so anything fixing or working on parts of this are fine; there's a lot of text to go through, and a lot of stuff to improve, so partial pull pull requests are obviously fine.

hey a small thing insted of using .txt we can use .md

**Comment by LunarWatcher** [comment]
Using txt is a Vim convention; https://vimhelp.org/helphelp.txt.html#help-writing

The files in question are also accessible from inside Vim, which is why they're formatted the way they are. The link also includes the format details.

Switching to markdown would require a lot more work, because we'd realistically need to make an entire standard for tags and whatnot, and somehow make it work when distributed, and I'd rather not reinvent the wheel with this particular problem. See: https://www.reddit.com/r/vim/comments/dxmpa6/writing_tagged_documentation_in_vim/

**Comment by LunarWatcher** [comment]
You can still work on this, I just realized a bit after the fact that assigning people to an issue this open-ended doesn't particularly make sense :')
