### ISSUE TITLE
Issue tracker

### ISSUE THREAD

**Issue by LunarWatcher** [LunarWatcher/auto-pairs#5]
Because I can't copy issues with little effort.

Because the issue tracker is a mess of duplicates, possibly handled issues, and issues unrelated to the plugin (such as people not understanding basic aspects of Vim), some issues are going to be filtered out of this list purely because I can.

**Comment by LunarWatcher** [comment]
Feature request:

| Upstream ID | Status |
| --- | --- |
| 310 | Planned |
| 205 | Maybe (alternatives exist, might be a good place to apply the  [UNIX philosophy](https://en.wikipedia.org/wiki/Unix_philosophy#Origin)) |

**Comment by LunarWatcher** [comment]
Bugs:

| Upstream ID | Comment | Status |
| --- | --- | --- |
| 302, 270 | Fixed by Krasjet's changes when `g:AutoPairsCompleteOnSpace` is set to 1 | Done |
| 299 | | Investigating |
| 290 | See the conflicts bit in the plugin documentation | By design |
| 283 | Seems really prone to false positives. | Open for discussion - declined otherwise |
| 277 | | Investigating |
| 268 | | Investigating |

(Note: investigating may refer to issues that aren't currently being worked on. Just means it's planned)

**Comment by LunarWatcher** [comment]
Backlog:

| Upstream ID | Comment |
| --- | --- |
| 276 | |
| 171 | I don't use neovim, and I can't reliably test it. If anyone wants to fix this, PRs are welcome - I won't be doing it |

**Comment by LunarWatcher** [comment]
Completed or otherwise handled, but never closed:

| Upstream ID | Comment
| --- | --- |
| 196 | `<M-p>` toggles autopairs, and therefore solves the issue. Equivalent to any other keybind |

**Comment by LunarWatcher** [comment]
Other weirdness to investigate:

| Upstream ID | Comment |
| --- | --- |
| #150 (PR) | Adds several features present in Krasjet's PR, but contains a patch to #133. Weird because this solves several upstream issues, but wasn't merged or even acknowledged by jiangmiao, in spite of it being before their disappearance. Might have to cherry-pick commits from this one, or just bite the bullet and do conflict resolution |

**Comment by LunarWatcher** [comment]
Pull requests:

| Upstream ID | Comment | status |
| --- | --- | --- |
| #201 | Conflict | Closed |
| #284 | Conflict, substantial performance issues | Closed |
| #303 | | Merged: #3 |
| #304, #249 | | Conflict with the same fix at fork creation |
| #274 | | **Investigating** |
| #273 | Somewhat sus this might negatively affect double quote use in vimscript | **Investigating** |
| #298 | | **Investigating** |
| #153 | Niche? There's also a way to remap `<cr>` if there's a conflict, which I'm guessing was the intent? Admittedly in a substantially less portable way. | Closed |
| #286 | I don't really like this. Also, `f"` autocompletes fine, so there might be a deeper issue. Even then, this would be more suited for a language-specific addition than a global addition. | Closed |
| #150 | Conflict resolution hell; see failed #6. Only an issue due to 4 years of changes while the PR was ignored. Reimplementing from scratch | Closed |
| #146 | The lack of buffer variable use makes this obsolete. | Closed |
| #145 | Would definitely make flymode less annoying. | **Investigating** |
| #144 | | Merged |
| #127 | Too likely to cause false positives; use an `autocmd FileType` instead | Closed |
| #120 | | Conflict with Krasjet |
| #291 | Initialization is on a per-buffer basis. Initializing that early does nothing in the long run. I understand there's an issue here, but this probably isn't the solution. | Closed, issue if the problem exists in a reproducible way appreciated. |
| #266 | Might be useful. | **Investigating** |

Obsolete PRs as a consequence of changes made to this fork that make these issues **completely** incompatible: 218

Other issues: 
| ID | Comment
| --- | --- |
| 58 | Source repo is gone, can't merge it. Also extremely confused wrt. context |
| 56 | Same situation as 58 |

**Comment by chindraba-work** [comment]
Reference to #205: Unix Philosophy seems quite proper here. I'd call it declined, closed, or done.

In concept (closing what's been opened) it looks the same. It isn't really the same thing though. AutoPairs matches "pairs" of characters, not arbitrary strings of unbounded length and complexity.

In addition to the Tim Pope reference in the Non-goals section of the README, I'd recommend a pointer to [vim-closetag](https://github.com/alvan/vim-closetag).

**Comment by LunarWatcher** [comment]
HTML also went a bit out the window when I discarded endwise rules (too complex, ends up being a bad drop-in "replacement" for snippets or other better suited plugins). Forgot updating it here though -- too much to keep track of :')

**Comment by LunarWatcher** [comment]
Gonna close this for the time being. Reasonably certain I've gotten through what I can. The backlog is still a bit of a problem, but not much I can do about it atm. Can rather revisit those issues later if they're reopened
