### ISSUE TITLE
Close brackets are added even when the next character is alphanumeric

### ISSUE THREAD

**Issue by evprkr** [LunarWatcher/auto-pairs#58]
Hi, I found your plugin via an issue on the original plugin regarding this specific issue. After removing the old one and installing this one, I'm still having the same issue, eg:

Current functionality:
`VariableN|ame` (insert open bracket) `VariableN{|}ame`

Desired result:
`VariableN|ame` (insert open bracket) `VariableN{|ame`

I wanted to note that I found a plugin called Delimitmate that DOES have this functionality, however I don't like to use it because it doesn't automatically indent the next line after a bracket when pressing return.

**Comment by LunarWatcher** [comment]
It's disabled by default. Did you enable it?

https://github.com/LunarWatcher/auto-pairs/blob/8c4a035165a5af726bbcc60c78821a66083a9f98/doc/AutoPairs.txt#L628-L641
