### ISSUE TITLE
Can't delete in pairs 

### ISSUE THREAD

**Issue by hungpham3112** [LunarWatcher/auto-pairs#61]
I used your plugin for 6 months but after update I can't delete in pairs anymore. I changed to ```jiangmiao/auto-pairs``` and it's ok. I think perhaps your recent PR break this feature.

With your auto-pairs version:
https://user-images.githubusercontent.com/75968004/170621491-a9d2a6da-1114-4aa9-aac9-8ef23c2e9a2d.mp4

With jiangmiao/auto-pairs:

https://user-images.githubusercontent.com/75968004/170621777-aedd1186-4691-4a8a-95a0-9dd5382010c6.mp4

**Comment by LunarWatcher** [comment]
Did you enable pair deletion?

**Comment by hungpham3112** [comment]
> Did you enable pair deletion?

I thought it's enabled by default, because I use this plugin for 6 months with no issue and today it happens. How can I enable it?

**Comment by LunarWatcher** [comment]
https://github.com/LunarWatcher/auto-pairs/blob/6c1deb2fe8501e1c4de31732f04eaede31b9021d/doc/AutoPairs.txt#L112

**Comment by hungpham3112** [comment]
> https://github.com/LunarWatcher/auto-pairs/blob/6c1deb2fe8501e1c4de31732f04eaede31b9021d/doc/AutoPairs.txt#L112

Thanks for your help. I got it

**Comment by LunarWatcher** [comment]
For the record, though, it _is_ weird that it took 6 months for it to suddenly "realize" it's disabled by default. It being disabled by default has been a fact for more or less the entire lifetime of this fork, and I haven't had much of a chance to work on the code for a while either. Been dragged in various directions by circumstance, but that doesn't matter all that much. The point is, a recent code update didn't cause it, at least if you've been mostly staying up-to-date. What caused it will likely remain a mystery, unless you happen to have made some changes to your dotfiles recently, and also have them saved in a way that lets you revisit those changes.

It's not super important anyway; as long as it works, that's really all that matters when it's an apparent one-off bug
