### ISSUE TITLE
Regex issue with new tex multibyte pairs

### ISSUE THREAD

**Issue by HawkinsT** [LunarWatcher/auto-pairs#74]
**OS**: Arch Linux

**What vim? (+ version)**: nvim 0.9 nightly

**Describe the bug**
Since adding the new latex multibyte pairs recently, `\( \)` and `\[ \]`, there is an issue with, for example, typing `\(` and then hitting ~~backspace~~ `\` [edited to correct bug reproduction method], which will show the error:

```
Error detected while processing function autopairs#AutoPairsInsert[85] .. autopairs#Insert#checkClose:
line 34:
E54: Unmatched (
```

This error can be avoided by overriding the new multibyte pair handling with the below, which works as expected:

```lua
vim.g.AutoPairs = vim.fn["autopairs#AutoPairsDefine"]({
    { open = [[\\(]], close = "\\)", filetype = "tex" },
    { open = [[\\[]], close = "\\]", filetype = "tex" },
})
```

**Comment by LunarWatcher** [comment]
The pairs aren't evaluated as regex anymore. The pairs are processed as if it could be regex, but it appears that escaping results in the total being unescaped and therefore causing errors. The TL;DR: is remove the double escape (I assume `[[\\(]]` is syntax for a string literal `'\\('`; you just want `'\('` now). The escaping issue remains an annoyance though, but I'll have to whip out a home-made escape solution to fix it. The main problem as your pair definitions stands now is that it wouldn't match `\(`

That said, you don't need to define those two manually anymore. They're added by default (and those defaults are verified by tests)

**Comment by HawkinsT** [comment]
Sorry, to explain better, my issue is with the new baked in multibyte pairs you've recently added. My code above fixes the issue by overwriting auto-pairs new baked in multibyte pairs that have this issue. `[[\\(]]` is equivalent to `"\\\\("`. I'll try with a fully minimal config though as I'm surprised the new pairs are passing tests.

**Comment by LunarWatcher** [comment]
> [[\\(]] is equivalent to "\\\\("

Yes, which is `'\\('` (single quotes in Vimscript are raw strings, and it's much easier to talk about raw strings). Regex pairs are disabled by default, which means your `\\(` is escaped to `\\\\(` (all raw strings), which still shouldn't be evaluated as regex to yield problems. I can't reproduce in Vim with `\\[` or `\[` (the first of which only triggers when `\\[` is typed, and the latter only triggers when `\[` is typed, as expected)

The tests do not run in Neovim, because it's a pain in the ass to set up , but looks like I have to set some up now. My best guess is that Neovim screwed up the regex engine defaults (or the regex engine itself), both of which could be reasons for it to happen. 

Unfortunately, the `\\[` and `\\(` tests I did confirms the escape system is working as intended. Unless the regex engine has changed, there's no way the escaping should lead to regex evaluation

**Comment by HawkinsT** [comment]
Thanks. I'm not getting this issue on a completely minimal config (only auto-pairs loaded) so I'm now playing around with what may be the cause, sorry, I should have done this initially, but I'll report back here once I work out the issue or how to reproduce it.

**Comment by LunarWatcher** [comment]
Seems like automated tests are off the table. The test framework is incompatible with neovim. Gonna have to poke around manually, which will take a while

**Comment by HawkinsT** [comment]
No problem, thanks for you help. I'll try to have a further look at it too. At least there is a workaround for now. I assume this issue still isn't present with backslash (rather than backspace as I previously, incorrectly, stated) in vim then?

**Comment by LunarWatcher** [comment]
Strange, I can reproduce it now. Looks like it's a jump thing

**Comment by LunarWatcher** [comment]
That should do the trick. I'll also have to look around for other missing escapes, but this particular bug is gone

**Comment by HawkinsT** [comment]
That fixes it, thanks. It's not ideal behaviour since math mode in latex will almost always contain backslashed command and typing backslash will automatically jump over the closing `\)`, even with a space before the closing pair, e.g. `\( | \)` (this doesn't occur with my alternative g:AutoPairs command above), but at least it doesn't error now and works as expected.

**Comment by LunarWatcher** [comment]
Hm, I forgot about that. Might be worth disabling jumping altogether for those pairs? Should be trivial to do. Alternatively, I should be able to set the jump key to `)` instead, if that makes more sense.

The only other option is setting `b:AutoPairsSearchCloseAfterSpace` (the help doc is under `g:AutoPairsSearchCloseAfterSpace`) manually for the tex filetype, but that has consequences for all pairs, and wouldn't be a default I'd set in auto-pairs itself

**Comment by LunarWatcher** [comment]
Should be disabled now. Also found a minor annoyance with how jump mapping was handled that prevented it from working right away, but whatever. All good now (in theory)
