### ISSUE TITLE
Not getting auto completed parenthesis just before a quote

### ISSUE THREAD

**Issue by lemerchand** [LunarWatcher/auto-pairs#75]
Hi there. I recently changed `g:AutoPairsCompleteOnlyOnSpace` to 1 so that I wouldn't have auto-pairs before alphanumeric characters. This worked however since then I do not get auto-pairs just before quotation marks. For example:

```
"Hello world! ("
'Shake your groove thang! {'
```

would not introduce a closing parenthesis.

**Comment by LunarWatcher** [comment]
Well, no. When you enable that variable, it needs some type of whitespace to trigger. Quotes aren't whitespace

**Comment by lemerchand** [comment]
I see what you mean, but it's there any way to make auto-pairs function that way, that is, no trigger on alphanumeric specifically? If not is that a feature request you'd be willing to entertain?

**Comment by lemerchand** [comment]
Awesome, and thanks for your work!

**Comment by LunarWatcher** [comment]
Added now. Included example usage for your use-case in the docs as well (and a later commit expands that beyond ascii use), so you can just copy-pasta whichever makes most sense  for your use

**Comment by lemerchand** [comment]
Damn, you are the bees knees. I'll update and try it out a little later today. Thank you so, so much!

**Comment by lemerchand** [comment]
Works like a charm! Thank you again for the quick response and FR!
