### ISSUE TITLE
Changing variables has no effect on functionality of the plugin

### ISSUE THREAD

**Issue by KaXMaXimum** [LunarWatcher/auto-pairs#76]
The only explanation I have for this problem is that i'm running SpaceVim and that this somehow conflicts with the functionality of Autopairs, but that would be weird since this is the only plugin I haven't been able to configure.

I was looking to add custom pairs to autopairs, and adding `let g:AutoPairs = AutoPairsDefine(...)` in my config with the original autopairs plugin wasn't having any effect. That's when I found this fork and I am noticing the same issues.

Setting `g:AutoPairsMapBS=1` wouldn't change the backspace keybind, although echoing it's value showed that it is indeed set to 1 and changing the keybind myself as shown in the documentation worked perfectly. The same thing is happening with setting my own custom `g:AutoPairs`. I even tried setting it to only be `g:AutoPairs = {'<':'>'}`, and while echoing it showed that it has been set properly, all of the standard pairs were active and < was never paired with >.

I also noticed that changing the default pairings in the original autopairs.vim directly worked while setting the variables later didn't. I apologize if my setup is causing this (or if the syntax I wrote here isn't too exact, but I did make sure everything was written correctly) but it would still be interesting to figure out what exactly is causing this. Changing variables for other plugins has always worked fine (e.g with UltiSnips), which is why I am even more confused as to what is happening.

Adding `'\{': {'close': '\}', 'mapclose': 0}` to Variables.vim directly in the InitVariables function works perfectly, but I'm not comfortable with this since this wouldn't be a direct part of my config but rather a direct modification of the plugin

**Comment by LunarWatcher** [comment]
This wouldn't happen to occur exclusively in Rust files, would it?

**Comment by KaXMaXimum** [comment]
Seems that that was the problem, I can set AutoPairs settings in another function which is called earlier on and the settings now stick. Only problem is that the function AutoPairsDefine isn't defined yet, so setting the variable manually works but doing it through the function doesn't. I'll explore this further and inform you, might be nice to have in the documentation in case someone else is running a similar setup

**Comment by LunarWatcher** [comment]
Strange.

> Is it possible that this is too late for AutoPairs?

Only if it happens after buffer creation, but you wouldn't see that if you open a new buffer while Vim is already running. I'm not entirely sure when the autocmd executes relative to buffer creation though, but it'd only affect the first thing you edit after opening vim at worst. 

`b:AutoPairs`, which actually contains the pairs used, is created from `g:AutoPairs`, and is then used to populate another internal variable I don't remember the name of, but it doesn't matter in this case. As you've described it, and from the little I looked at spacevim's source code, no buffer variable modification is involved, so `b:AutoPairs` is indicative on its own.

What's the output of `:verbose imap c` (or any other key you have mapped), and `:echo b:AutoPairs`?

> Only problem is that the function AutoPairsDefine isn't defined yet, so setting the variable manually works but doing it through the function doesn't.

As long as the plugin has been loaded by the time your code executes, it's fine. This fork uses autoload functions, so calling `autopairs#AutoPairsDefine()` makes Vim automatically load the file to avoid the undefined functions that plagued the original auto-pairs.

**Comment by KaXMaXimum** [comment]
Good point on buffer creation. Setting the variable in the "after" bootstrap function, which is called on VimEnter apparently, has no effect on the mappings at first. After opening a new .tex file in a new buffer I get this
```
i  c           *@<C-R>=autopairs#AutoPairsInsert('c')<CR>
        Last set from ~/.cache/vimfiles/.cache/init.vim/.dein/autoload/autopairs.vim line 556
```
as the output of `:verbose imap c` and all mappings work as expected.

**Comment by LunarWatcher** [comment]
So it's an init order problem causes by spacevim's config style? Not really much to document here then; would probably be good if spacevim added some more hooks though

**Comment by KaXMaXimum** [comment]
Yeah kinda annoying but it isn't too much of a big deal. For now I've set my personal config file to also be called on BufEnter instead of VimEnter, it doesn't seem to cause any problems in my use case and everything works perfectly. I was wondering if I could set the necessary AutoPairs functions to also be called once on VimEnter (obviously not by default in the plugin but only for my config) since it seems like it would be lighter than calling my own config on BufEnter every time, but I couldn't find out how/ when this happens by looking at the plugin code.

It would be nice to try out this alternative solution if possible, if not I'd close this issue as we've figured out what causes it and I've managed to make it work in my specific case.

**Comment by LunarWatcher** [comment]
If you have a way to inject stuff early, you can take advantage of the init hook to initialise variables that way:

https://github.com/LunarWatcher/auto-pairs/blob/40ba32f1c35bd8e5a8dfa95ae808b7d03de220bc/doc/AutoPairs.txt#L899-L924

I recommend some access control variable though (or possibly checking `if exists("g:AutoPairsLoaded")` to determine the edits, but that still requires it to be compatible with spacevim's control flow.
