### ISSUE TITLE
 Delete both parentheses at once

### ISSUE THREAD

**Issue by IC0hO** [LunarWatcher/auto-pairs#88]
When "void f" is typed and then the "(" character is entered, it will automatically complete the parentheses, resulting in "void f()" with the cursor positioned between the parentheses. Now, with "void f()" and no content inside the parentheses, if you want to delete the parentheses, you can only delete the opening parenthesis first, and then move the cursor to delete the right parenthesis. In contrast, VSCode allows you to delete both the left and right parentheses at once.

Therefore, it would be desirable to have a feature where, in a case like "void f()" with the cursor positioned between the empty parentheses, pressing the backspace key could delete the entire pair of parentheses in one step.

**Comment by LunarWatcher** [comment]
Already exists, but it's disabled by default. See #61
