### ISSUE TITLE
Trigger abbreviations when inserting pair signs

### ISSUE THREAD

**Issue by Val95240** [LunarWatcher/auto-pairs#93]
Hey ! I've been using this plugin for a while now, and it works perfectly, thanks for the work !
However, I noticed a small issue recently: because the plugin remaps all pair signs in insert mode, it breaks the default abbreviation expansion in Vim (because it seems `<C-R>` does not expand them).
From what I've seen, I think the only necessary thing to fix this would be to add a `<C-]>` before the `<C-R>` in the "inoremap" in the autopairs#AutoPairsMap() function in `autoload/autopairs.vim`.
Would it be possible to include this modification, or would that break other parts of the plugin ?
Thanks !

**Comment by LunarWatcher** [comment]
Should be fixed. Can you update and check? I had some trouble getting basic abbreviations to cooperate with me, so not entirely sure if the fix also deals with whatever abbreviations you use. The fix worked on `abbr (a`, `abbr a(`, and `abbr a(b)` at least

**Comment by Val95240** [comment]
Works perfectly for me, thanks a lot for the quick fix !
